//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skidor4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chiplink
    {
        public int id { get; set; }
        public Nullable<int> person_id { get; set; }
        public int chip_id { get; set; }
        public int price_id { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
    
        public virtual chips chips { get; set; }
        public virtual persons persons { get; set; }
        public virtual prices prices { get; set; }
        public virtual bool isActive { get; set; }
    }
}
