//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skidor4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class covers
    {
        public int pk_id { get; set; }
        public int fk_station_id { get; set; }
        public Nullable<int> fk_chip_id { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual chips chips { get; set; }
        public virtual stations stations { get; set; }

        public virtual bool isActive { get; set; }
        public virtual string noChip { get; set; }
        public virtual DateTime timeTest { get; set; }
        public virtual string onlyDate { get; set; }
        public virtual bool isEquipment { get; set; }
        public virtual string dayFilter { get; set; }

    }
}
