//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skidor4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public int pk_id { get; set; }
        public string name { get; set; }
        public int fk_chip_id { get; set; }
    
        public virtual chips chips { get; set; }
        public virtual bool isActive { get; set; }
        public virtual DateTime time { get; set; }
    }
}
