//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Skidor4.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class scoreboard
    {
        public int pk_id { get; set; }
        public int fk_chip_id { get; set; }
        public int fk_track_id { get; set; }
        public System.DateTime start_time { get; set; }
        public System.DateTime end_time { get; set; }
    
        public virtual chips chips { get; set; }
        public virtual tracks tracks { get; set; }
        public virtual string time { get; set; }
        public virtual string speed { get; set; }
        public virtual string alias { get; set; }
        public virtual string km { get; set; }
        public virtual int placement { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public double Sum { get { return ((DateTime)end_time - (DateTime)start_time).TotalSeconds; } private set { } }
    }
}
